# Menu 目錄
menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  推荐||fas fa-list:
   #  电影: /movies/ || fas fa-movies
    音乐: /music/ || fas fa-music
    书单: /books/ || fa-solid fa-book
    # bilibili: /bangumis/ || fa-brands fa-bilibili
   #  游戏: /games/ || fas fa-games
  友链: /link/ || fas fa-link
  留言板: /comments/ || fas fa-paper-plane

## Favicon（网站图标）
favicon: /img/book-open-reader-solid.svg

## 头像
avatar:
  img: /img/sun.webp
  effect: false

## 主页封面图
index_img: # /img/home_bg.webp

# Footer Background,这里显示为true是为了显示页脚灯罩
footer_bg: true

# Website Background (設置網站背景)
# can set it to color or image (可設置圖片 或者 顔色)
# The formal of image: url(http://xxxxxx.com/xxx.jpg)
background: url(https://lcw0320.github.io/img/home_bg.webp)

cover:
  # display the cover or not (是否顯示文章封面)
  index_enable: true
  aside_enable: true
  archives_enable: true
  # the position of cover in home page (封面顯示的位置)
  # left/right/both
  position: both
  # When cover is not set, the default cover is displayed (當沒有設置cover時，默認的封面顯示)
  default_cover:
    # - https://localhost:4000/img/home_bg.webp


## 社交图标
social:
  fa-brands fa-github : https://github.com/lcw0320 || Github || '#24292e'
  fa fa-book-open: https://blog.csdn.net/weixin_51146207 || CSDN
  # fas fa-envelope: mailto:xxxxxx@gmail.com || Email || '#4a7dbe'

# Lazyload (圖片懶加載)
# https://github.com/verlok/vanilla-lazyload
lazyload:
  enable: false
  field: site # site/post
  placeholder:
  blur: false

## 文章末尾分享功能
sharejs:
  enable: true
  sites: facebook,twitter,wechat,weibo,qq 

## 代码样式
highlight_theme: mac  #  darker / pale night / light / ocean / mac / mac light / false 代码主题
highlight_copy: true # 复制按钮
highlight_lang: true # 是否显示代码语言
highlight_shrink: false # true: 代码块默认不展开 / false: 代码块默认展开 | none: 展开并隐藏折叠按钮
highlight_height_limit: false # unit: px
code_word_wrap: true #代码自动换行，关闭滚动条

## 调整侧边栏位置
aside:
  enable: true
  hide: true
  button: true
  mobile: true # display on mobile
  position: right # left or right 
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/lcw0320
  card_announcement:
    enable: false
    content: This is my Blog

## 标签外挂
note:
  # Note tag style values:
  #  - simple    bs-callout old alert style. Default.
  #  - modern    bs-callout new (v2-v3) alert style.
  #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
  #  - disabled  disable all CSS styles import of note tag.
  style: simple
  icons: false
  border_radius: 3
  # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
  # Offset also applied to label tag variables. This option can work with disabled note tag.
  light_bg_offset: 0


# 豆瓣外挂
douban:
   meta: true
   movies_img: https://fastly.jsdelivr.net/gh/jerryc127/butterfly_cdn@2.1.0/top_img/movie.jpg
   books_img: https://fastly.jsdelivr.net/npm/blog-gallery@1.0.0/1/20200206161657.webp

## 动态特效
inject:
  head:
    - <link rel="stylesheet" href="/css/custom.css" media="defer" onload="this.media='all'">
  bottom:
  ## 樱花飘落效果
  #  - <script async src="https://npm.elemecdn.com/tzy-blog/lib/js/other/sakura.js"></script>
  ## 星空背景
  #  - <canvas id="universe"></canvas>
  #  - <script defer src="/js/universe.js"></script>

## 鼠标点击特效
# Typewriter Effect (打字效果)
# https://github.com/disjukr/activate-power-mode
activate_power_mode:
  enable: false
  colorful: true # open particle animation (冒光特效)
  shake: true #  open shake (抖动特效)
  mobile: false

# Mouse click effects: fireworks (鼠标点击效果:萤火特效)
fireworks:
  enable: true
  zIndex: 9999 # -1 or 9999
  mobile: false

# Mouse click effects: Heart symbol (鼠标点击效果: 爱心)
click_heart:
  enable: false
  mobile: false

# 自助信阀式留言板
# see https://akilar.top/posts/e2d3c450/
envelope_comment:
  enable: true #控制开关
  custom_pic:      
    cover: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/violet.jpg #信笺头部图片
    line: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/line.png #信笺底部图片
    beforeimg: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/before.png # 信封前半部分
    afterimg: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/after.png # 信封后半部分
  message: #信笺正文，多行文本，写法如下
    - 有什么想问的？
    - 有什么想说的？
    - 有什么想吐槽的？
    - 哪怕是有什么想吃的，都可以告诉我哦~
  bottom: 自动书记人偶竭诚为您服务！ #仅支持单行文本
  height: #1050px，信封划出的高度
  path: #【可选】comments 的路径名称。默认为 comments，生成的页面为 comments/index.html
  front_matter: #【可选】comments页面的 front_matter 配置
    title: 留言板
    comments: true


# copy settings
# copyright: Add the copyright information after copied content (複製的內容後面加上版權信息)
copy:
  enable: true # 是否开启网站复制权限
  copyright:  # 复制的内容后面加上版权信息
    enable: false  # 是否开启复制版权信息添加
    limit_count: 50 # 字数限制，当复制文字大于这个字数限制时

# 赞助功能
reward:
  enable: false
  QR_code:
     - img: /img/favicon.png
       link:
       text: 微信
     - img: /img/favicon.png
       link:
       text: 支付宝

# Inject the css and script (aplayer/meting)
aplayerInject:
  enable: true
  per_page: true

